BASE = '''subject_definitions:
<Picture 1> Fixed 柳沟寺 study: writing desk and oil lamp left, paper window left-rear, latched wooden door centered, bed right.
<Picture 2> 孙生 (S1), late-20s scholar, gray-blue robe, same face and costume.
<Picture 3> 山魈 (S2), huge yellow-brown creature, giant claw and sparse long teeth.
<Picture 4> Door, quilt, short knife and claw-mark effects.

summary:
{summary}

retention_analysis:
Preserve the exact room geometry, centered door, door latch, left desk and right bed from the references. Preserve S1 face and costume. Live-action historical cinema; no subtitles, logos, watermarks, modern objects, extra people, or music.

detailed_description:
{detail}

overall_soundscape:
{sound}

non_diegetic_music:
N/A - no score.'''

PROMPTS = [
BASE.format(summary='Cold open: Sun Sheng is dragged across the stone floor toward a single solid door that stays latched.', detail='Use the supplied keyframe as the exact composition. The centered door is one solid closed wooden panel with zero gap and zero exterior light for every frame; the metal latch never moves. S1 lies on the floor and grips the same quilt that runs continuously from the disordered right bed to the lower door seam. [Shot 1] Near darkness and a low locked camera. [Shot 2] Only one enormous yellow-brown claw reaches under the absolutely closed door, hooks the quilt edge, and retracts; no body or face. [Shot 3] Five dark brown wood-colored claw grooves appear on the door, with no red, blood, or wet shine. End on S1 gasping and a brief dark hold. No curtain motion, no extra people, no door opening.', sound='Black-screen quilt drag, stone scrape, one low nonverbal resonance, wood scratching, S1 terrified breathing. No intelligible dialogue.'),
BASE.format(summary='Hours earlier, Sun Sheng returns to the abandoned Liugou Temple study and prepares the room.', detail='Use the supplied clean keyframe as the exact composition and preserve its room geometry. Exactly one human appears: S1, Sun Sheng, late-20s scholar in the same gray-blue robe. No animal, no fur, no monkey, no demon, no Shanxiao, no creature-like shadow, no reflection, no family member, no duplicate person, and no extra figure at any time. [Shot 1] Dusk wide shot; S1 enters from frame right. [Shot 2] He brushes dust from the left desk, clears the left paper window sill, unfolds the disordered bedding on the right bed, and lights the oil lamp. [Shot 3] He lies down; camera confirms desk left, one closed centered door with latch, bed right. The door remains closed throughout. Keep the clean photographic composition stable; do not invent a creature on the bed or floor.', sound='Dry leaves, broom, cloth, floor creaks, oil lamp flutter, distant mountain wind. No dialogue.'),
BASE.format(summary='The first wind reaches the sleeping scholar.', detail='[Shot 1] S1 sleeps on the right bed. A deep mountain gust makes the oil flame lean toward the centered door. [Shot 2] The latch stays still while wet boot sounds stop outside. [Shot 3] S1 opens his eyes and hides the short knife under the pillow. Only S1 is visible; no creature enters.', sound='Wind through paper, latch rattle, two heavy boot impacts, controlled breathing. No dialogue.'),
BASE.format(summary='Four waves of wind and footsteps approach through the temple.', detail='[Shot 1] Hold S1 on the right bed and the closed center door. Sound travels from distant gate to courtyard, corridor, then寝门. [Shot 2] Each pause is closer; the door opens only a narrow black slit at the final beat. Never reveal a face or full creature. No family.', sound='Four spatially distinct wind waves, four increasingly near boot patterns, hinge strain. No dialogue.'),
BASE.format(summary='The Shanxiao bends through the centered doorway and studies the room.', detail='[Shot 1] S2 bends under the centered lintel and enters, nearly touching the beam. S1 recoils on the right bed. [Shot 2] S2 circles once, giant mouth opening without words; lamp glass trembles. [Shot 3] S2 stops beside the quilt and lowers its face. Keep S2 center and S1 right; no family, no blood.', sound='Door groan, heavy footfalls, deep throat resonance, lamp vibration. No intelligible speech.'),
BASE.format(summary='The quilt moves before the creature touches it.', detail='[Shot 1] S1 holds his breath on the right bed while the quilt slides toward the centered door by an unseen force. [Shot 2] S2 remains beside the bed, watching; the room geometry does not move. [Shot 3] S1 understands the door is not a barrier and draws the short knife. No family, no blood.', sound='Fabric drag, floor scrape, short inhale, low nonverbal resonance. No dialogue.'),
BASE.format(summary='Sun Sheng stabs the Shanxiao once, but the blow does not stop it.', detail='[Shot 1] S1 clearly draws the short knife. [Shot 2] He thrusts once into S2 abdomen; the blade strikes with a hollow stone impact, with no blood or red liquid. [Shot 3] S2 looks at the blade and grabs the quilt. Preserve clean bedding and fixed door.', sound='Knife draw, stone-like impact, one roar without words, bed wood creak. No intelligible dialogue.'),
BASE.format(summary='The Shanxiao drags Sun Sheng toward the still-latched door.', detail='[Shot 1] S2 retreats toward the centered door while dragging the quilt; S1 slides from the right bed across the stone floor. [Shot 2] S1 grips the threshold with one hand and the knife with the other. The door remains closed and the latch remains inside. [Shot 3] Five claws pierce the door panel from the impossible far side. No family, no open doorway, no blood.', sound='Quilt drag, stone scrape, wood cracking, door vibration, S1 breath. No dialogue.'),
BASE.format(summary='At the threshold Sun Sheng shouts once as the Shanxiao pulls the quilt through the closed door.', detail='[Shot 1] S1 is half across the threshold, face against the floor, door still shut and latched. [Shot 2] S1 shouts exactly: <d>[Chinese] 妖物，退开！</d>. [Shot 3] S2 claws seize the quilt edge through the seam; the lamp goes out, leaving moonlight on the claws. No blood, no extra voices, no demon dialogue.', sound='Only S1 says the single line 妖物，退开！; violent wood vibration, cloth tear, nonverbal roar. No music.'),
BASE.format(summary='Family members break the left paper window and find the locked room changed.', detail='[Shot 1] Three indistinct family silhouettes approach from outside and enter only through the torn left paper window with a lamp. The centered wooden door remains shut and latched. [Shot 2] Lamp beam finds S1 on the floor and the quilt caught at the door seam; S2 is absent. [Shot 3] No one enters through the center door and no readable dialogue.', sound='Running feet, paper tearing, lamp metal, muffled gasps, S1 breathing. No clear words.'),
BASE.format(summary='Daylight reveals physical evidence while the door latch has never moved.', detail='[Shot 1] Dawn push toward the centered door. Family lifts S1 but remains partial and left/right of the room. [Shot 2] Show short knife bent, quilt fibers through the seam, and five deep claw grooves through the wood. [Shot 3] Close on the untouched inner latch. No creature, no blood, no dialogue.', sound='Wood splinters, fabric pull, restrained breathing, distant temple bell. No intelligible dialogue.'),
BASE.format(summary='Sun Sheng leaves, hears a second pair of boots, and the empty door appears to learn the latch.', detail='[Shot 1] S1 exits the temple path with satchel; exactly one human in the mountain road. [Shot 2] Wet footprints appear behind him with no body; he turns and finds only wind. [Shot 3] Cut back to the empty study: centered door closed, five claw grooves slowly extend upward toward the latch. No demon body, no new person, no readable text.', sound='Footsteps, wind, one distant bell, a second unseen boot pattern, final wood scratch. No dialogue.'),
]
